### ISSUE TITLE
Add OpenUserJS badge

### ISSUE THREAD

**Issue by ghost** [NatoBoram/youtube-comment-blacklist#3]
[![OpenUserJS](https://img.shields.io/badge/dynamic/json?color=%232c3e50&label=OpenUserJS&query=%24.OpenUserJS.installs%5B0%5D.value&suffix=%20installs&url=https%3A%2F%2Fopenuserjs.org%2Fmeta%2FNatoBoram%2FYouTube_Comment_Blacklist.meta.json)](https://openuserjs.org/scripts/NatoBoram/YouTube_Comment_Blacklist)

`[![OpenUserJS](https://img.shields.io/badge/dynamic/json?color=%232c3e50&label=OpenUserJS&query=%24.OpenUserJS.installs%5B0%5D.value&suffix=%20installs&url=https%3A%2F%2Fopenuserjs.org%2Fmeta%2FNatoBoram%2FYouTube_Comment_Blacklist.meta.json)](https://openuserjs.org/scripts/NatoBoram/YouTube_Comment_Blacklist)`

**Comment by NatoBoram** [comment]
Done!
