### ISSUE TITLE
Bug : 'simp' blacklist word matches simple, Simpson, etc

### ISSUE THREAD

**Issue by blurtrousers** [NatoBoram/youtube-comment-blacklist#5]
### Description

'simp' gets matched to common English words
https://www.thefreedictionary.com/words-containing-simp

Suggested code change in #4, may wish to remove '[^e]' as most words in the link above have L, but not E

### How to reproduce

1. Load comments for https://www.youtube.com/watch?v=9DN8rOUDr-c
2. Check javascript console
3. Note the line 'Removing "simp" : this is too simple lol'

### Environment

- Browser : Firefox
- Add-on : GreaseMonkey
- Operating System : Windows 10

**Comment by NatoBoram** [comment]
I see there's no word *ending* in `simp`, so I'll try using `/simp\b/i`. Thanks for the PR btw! 🎉
